name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install php-dev
    - name: phpize
      run: phpize
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test

