name: php55

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup docker container
      run: docker build -t ext -f ./.docker/Dockerfile.php55 .
    - name: phpize
      run: docker run -it --rm ext:lates

