name: several php versions

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-18.04, ubuntu-16.04 ]
        php: [ '5.5', '7.4' ]
    name: PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: withgod/setup-php@add-phpize
      with:
        php-version: ${{ matrix.php }}
    - name: phpize
      run: phpize
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test

